services:
  ytpodcast:
    build: .
    ports:
      - "${HOST_API_PORT}:${API_PORT}"
    environment:
      CACHE_DIR: /app/var/cache
      DOWNLOAD_DIR: /app/var/downloads
      YTDL_EXECUTABLE_PATH: yt-dlp
      YTDL_DEFAULT_FORMAT: bestaudio
    volumes:
      - ./var:/app/var
