services:
  ytpodcast:
    build: .
    ports:
      - "8459:8459"
    environment:
      DOWNLOAD_DIR: /app/var/downloads
      YTDL_EXECUTABLE_PATH: yt-dlp
      YTDL_DEFAULT_FORMAT: bestaudio
    volumes:
      - ./var:/app/var
